ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file ½ts𘚲ē𣜦.Ýôę𮞝a: invalid non-printable character U+DAFF6 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '³' (U+00B3) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+3000 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+AC8AF (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '±' (U+00B1) (<unknown>, line 1)
ERROR:root:Syntax error in file ő#Òé𘊗𭼲: invalid character '±' (U+00B1) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0083 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+548C4 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+548C4 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+548C4 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2000 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+3000 (<unknown>, line 2)
ERROR:root:Syntax error in file 1舊𧃳: invalid non-printable character U+3000 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file 㝦𧆙8ﺡUİ馌ñŖõĬü: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file ù: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file ù: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file ù: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file ù: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file ù: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+008C (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: expected an indented block after function definition on line 1 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: expected an indented block after function definition on line 1 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '×' (U+00D7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '×' (U+00D7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '×' (U+00D7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '×' (U+00D7) (<unknown>, line 1)
ERROR:root:Syntax error in file #Ő𢶱𤶼Ĥ;Q簳_: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file 𧴗: invalid non-printable character U+E66EF (<unknown>, line 1)
ERROR:root:Syntax error in file 𧴗: invalid non-printable character U+E66EF (<unknown>, line 1)
ERROR:root:Syntax error in file 𧴗: invalid non-printable character U+E66EF (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+009E (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '²' (U+00B2) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unmatched ')' (<unknown>, line 1)
ERROR:root:Syntax error in file dņŜāª𣋞쒤K톬Ċ: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file dņŜāª𣋞쒤K톬Ċ: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+C9746 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+009B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0092 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0092 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0092 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2005 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: invalid non-printable character U+009A (<unknown>, line 1)
ERROR:root:Syntax error in file 西]ņČu\o: unmatched ']' (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+4ADAF (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+4ADAF (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+13D45 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+13D45 (<unknown>, line 1)
ERROR:root:Syntax error in file Y: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file Y: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file Y: invalid character '±' (U+00B1) (<unknown>, line 1)
ERROR:root:Syntax error in file Y: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file 9: invalid non-printable character U+58271 (<unknown>, line 1)
ERROR:root:Syntax error in file 𤴾t: invalid non-printable character U+3C10C (<unknown>, line 1)
ERROR:root:Syntax error in file 𤴾t: invalid non-printable character U+3C10C (<unknown>, line 1)
ERROR:root:Syntax error in file 𤴾t: invalid non-printable character U+42EBE (<unknown>, line 1)
ERROR:root:Syntax error in file 𤴾t: invalid non-printable character U+42EBE (<unknown>, line 1)
ERROR:root:Syntax error in file 𤴾t: invalid non-printable character U+42EBE (<unknown>, line 1)
ERROR:root:Syntax error in file ŗ꙳ëĔ: invalid non-printable character U+2005 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+2005 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file -: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file á𰄋犱Ĥ: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file á𰄋犱Ĥ: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file á𰄋犱Ĥ: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file á𰄋犱Ĥ: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file á𰄋犱Ĥ: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file HĪĖ𝙮曖𭱛j隋ňĉ[«ŒĸĒŜQó: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file HĪĖ𝙮曖𭱛j隋ňĉ[«ŒĸĒŜQó: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+008D (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2005 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2005 (<unknown>, line 2)
ERROR:root:Syntax error in file 黖𤵯Ã&Ĕx鋂Ĭa¶Ó@: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file 黖𤵯Ã&Ĕx鋂Ĭa¶Ó@: invalid character '¶' (U+00B6) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¶' (U+00B6) (<unknown>, line 1)
ERROR:root:Syntax error in file 𘥢¾,ÜĄê𰏒ÀZ𭾒𠲮BÄ: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file 𘥢¾,ÜĄê𰏒ÀZ𭾒𠲮BÄ: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file 𘥢¾,ÜĄê𰏒ÀZ𭾒𠲮BÄ: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file 𘥢¾,ÜĄê𰏒ÀZ𭾒𠲮BÄ: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file Ň嵁Nő¼𥜝: invalid non-printable character U+205F (<unknown>, line 2)
ERROR:root:Syntax error in file Ň嵁Nő¼𥜝: invalid non-printable character U+205F (<unknown>, line 2)
ERROR:root:Syntax error in file Ň嵁Nő¼𥜝: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file Ň嵁Nő¼𥜝: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file @: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file @: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file @: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file RÛĠ濁8ĳJ𖼐: invalid non-printable character U+0088 (<unknown>, line 1)
ERROR:root:Syntax error in file åĿĪj: invalid non-printable character U+8E250 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+8E250 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+8E250 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+8E250 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+8E250 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0082 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¿' (U+00BF) (<unknown>, line 1)
ERROR:root:Syntax error in file Ĕį: invalid non-printable character U+0080 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0090 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0090 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0090 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E8963 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E8963 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E8963 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A8A79 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A8A79 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+F0722 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file JùŎĐŃ: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file JùŎĐŃ: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file JùŎĐŃ: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file JùŎĐŃ: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file JùŎĐŃ: invalid non-printable character U+2006 (<unknown>, line 4)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2006 (<unknown>, line 4)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2006 (<unknown>, line 4)
ERROR:root:Syntax error in file ŏ#Ĺ: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file ŏ#Ĺ: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file ŏ#Ĺ: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file {: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file {: unterminated string literal (detected at line 1) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2029 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2029 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file 𘢏Ïĳ: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file 𘢏Ïĳ: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file 𘢏Ïĳ: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file 8: invalid non-printable character U+202F (<unknown>, line 3)
ERROR:root:Syntax error in file 8: invalid non-printable character U+202F (<unknown>, line 3)
ERROR:root:Syntax error in file 8: invalid non-printable character U+202F (<unknown>, line 3)
ERROR:root:Syntax error in file 0: invalid non-printable character U+202F (<unknown>, line 3)
ERROR:root:Syntax error in file 0: invalid syntax (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '𐄨' (U+10128) (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid non-printable character U+D0621 (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid non-printable character U+D0621 (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid non-printable character U+D0621 (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid character '𐄨' (U+10128) (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid character '𐄨' (U+10128) (<unknown>, line 1)
ERROR:root:Syntax error in file û: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Ĭâ𫫟ōĦ: invalid non-printable character U+008A (<unknown>, line 1)
ERROR:root:Syntax error in file Aø𑿒_𬧖"ŀR½(ÌĽiŊķ: invalid non-printable character U+2004 (<unknown>, line 4)
ERROR:root:Syntax error in file Aø𑿒_𬧖"ŀR½(ÌĽiŊķ: invalid non-printable character U+2004 (<unknown>, line 5)
ERROR:root:Syntax error in file Aø𑿒_𬧖"ŀR½(ÌĽiŊķ: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+41240 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+41240 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+41240 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '½' (U+00BD) (<unknown>, line 1)
ERROR:root:Syntax error in file ļÔ렪: invalid non-printable character U+FDB9E (<unknown>, line 1)
ERROR:root:Syntax error in file ļÔ렪: invalid non-printable character U+FDB9E (<unknown>, line 1)
ERROR:root:Syntax error in file ļÔ렪: invalid non-printable character U+FDB9E (<unknown>, line 1)
ERROR:root:Syntax error in file ļÔ렪: invalid non-printable character U+009B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2003 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¥' (U+00A5) (<unknown>, line 1)
ERROR:root:Syntax error in file 𗑟Õ#«ļĝĵġĩ뤻ŏo: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file 𗑟Õ#«ļĝĵġĩ뤻ŏo: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+108E57 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+108E57 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+108E57 (<unknown>, line 1)
ERROR:root:Syntax error in file Ĥ: invalid character '¸' (U+00B8) (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid character '¸' (U+00B8) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¹' (U+00B9) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¹' (U+00B9) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¹' (U+00B9) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '¹' (U+00B9) (<unknown>, line 1)
ERROR:root:Syntax error in file 𫎳îÌ𣓵: invalid non-printable character U+D141B (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+D141B (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+D141B (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+D141B (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+D141B (<unknown>, line 1)
ERROR:root:Syntax error in file È: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file Ā𡠕ęÿ: invalid character '¸' (U+00B8) (<unknown>, line 1)
ERROR:root:Syntax error in file Ā𡠕ęÿ: invalid character '¸' (U+00B8) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file \: invalid non-printable character U+14A3C (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0095 (<unknown>, line 1)
ERROR:root:Syntax error in file VD?: invalid non-printable character U+FA0D2 (<unknown>, line 1)
ERROR:root:Syntax error in file VD?: invalid non-printable character U+FA0D2 (<unknown>, line 1)
ERROR:root:Syntax error in file VD?: invalid non-printable character U+FA0D2 (<unknown>, line 1)
ERROR:root:Syntax error in file ō𮛼ë: invalid non-printable character U+2000 (<unknown>, line 2)
ERROR:root:Syntax error in file ō𮛼ë: invalid non-printable character U+2000 (<unknown>, line 2)
ERROR:root:Syntax error in file ō𮛼ë: invalid non-printable character U+2000 (<unknown>, line 2)
ERROR:root:Syntax error in file ō𮛼ë: invalid non-printable character U+2000 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '´' (U+00B4) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E3652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E5B5B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E5B5B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E5B5B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+E5B5B (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+15669 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+15669 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+15669 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+15669 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+15669 (<unknown>, line 1)
ERROR:root:Syntax error in file KĜàħÝÿþ: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '®' (U+00AE) (<unknown>, line 1)
ERROR:root:Syntax error in file s敹Ú㬉Âꁾř1: invalid non-printable character U+76F0C (<unknown>, line 1)
ERROR:root:Syntax error in file s敹Ú㬉Âꁾř1: invalid non-printable character U+0091 (<unknown>, line 1)
ERROR:root:Syntax error in file s敹Ú㬉Âꁾř1: invalid non-printable character U+0091 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+0091 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+0091 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2002 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2002 (<unknown>, line 3)
ERROR:root:Syntax error in file Ĩđŋ: invalid non-printable character U+0081 (<unknown>, line 1)
ERROR:root:Syntax error in file Ĩđŋ: invalid non-printable character U+0081 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0089 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unexpected character after line continuation character (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unexpected character after line continuation character (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: unexpected character after line continuation character (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: expected an indented block after 'try' statement on line 1 (<unknown>, line 4)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 6)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 5)
ERROR:root:Syntax error in file Ő𐣵ā𘂈Üĵĕ𱋾𣑔q: invalid non-printable character U+F4355 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+F4355 (<unknown>, line 1)
ERROR:root:Syntax error in file ĭÑĀį21: invalid non-printable character U+0082 (<unknown>, line 1)
ERROR:root:Syntax error in file ĭÑĀį21: invalid non-printable character U+0082 (<unknown>, line 1)
ERROR:root:Syntax error in file ĭÑĀį21: invalid non-printable character U+0082 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+0082 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2007 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file İæᆀ𰲂Á: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file İæᆀ𰲂Á: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0098 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+200A (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+200A (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid character '§' (U+00A7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '§' (U+00A7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '§' (U+00A7) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+58797 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+58797 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+58797 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0080 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0080 (<unknown>, line 1)
ERROR:root:Syntax error in file Ĳ𥅊ĺ: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file äĦĒx: invalid non-printable character U+60B29 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file Ŋ\資𠜅Ő¿ÄX%ăyÇ: invalid non-printable character U+009C (<unknown>, line 1)
ERROR:root:Syntax error in file Ŋ\資𠜅Ő¿ÄX%ăyÇ: invalid non-printable character U+009C (<unknown>, line 1)
ERROR:root:Syntax error in file Ŋ\資𠜅Ő¿ÄX%ăyÇ: invalid non-printable character U+009C (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+84AF5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+00A0 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file M: invalid non-printable character U+E186C (<unknown>, line 1)
ERROR:root:Syntax error in file M: invalid non-printable character U+E186C (<unknown>, line 1)
ERROR:root:Syntax error in file M: invalid non-printable character U+96826 (<unknown>, line 2)
ERROR:root:Syntax error in file M: invalid non-printable character U+96826 (<unknown>, line 2)
ERROR:root:Syntax error in file ĉĻ𪂒𧵈𬜳": invalid non-printable character U+BB8BA (<unknown>, line 1)
ERROR:root:Syntax error in file ĉĻ𪂒𧵈𬜳": invalid non-printable character U+BB8BA (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2009 (<unknown>, line 2)
ERROR:root:Syntax error in file )Ê,«ĖÍ: invalid non-printable character U+52525 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '½' (U+00BD) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: expected an indented block after 'if' statement on line 1 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A5BDE (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A5BDE (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A5BDE (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+CAFC1 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+32F4A (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+103EE3 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+103EE3 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file 異: invalid non-printable character U+202F (<unknown>, line 4)
ERROR:root:Syntax error in file 異: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file 異: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+202F (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+79D68 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+79D68 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 1)
ERROR:root:Syntax error in file i: invalid non-printable character U+96457 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+96457 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+96457 (<unknown>, line 1)
ERROR:root:Syntax error in file 0: invalid non-printable character U+96457 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2028 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2028 (<unknown>, line 3)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0084 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0084 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+7E5A8 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+DB9C8 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+DB9C8 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+DB9C8 (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file į: invalid character '£' (U+00A3) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+14BC5 (<unknown>, line 1)
ERROR:root:Syntax error in file ¹: invalid non-printable character U+13F74 (<unknown>, line 1)
ERROR:root:Syntax error in file ¹: invalid non-printable character U+13F74 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '«' (U+00AB) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file ì: invalid non-printable character U+0081 (<unknown>, line 1)
ERROR:root:Syntax error in file ì: invalid non-printable character U+0081 (<unknown>, line 1)
ERROR:root:Syntax error in file ì: invalid non-printable character U+0081 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A2652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A2652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A2652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A2652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+A2652 (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+009E (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2008 (<unknown>, line 2)
ERROR:root:Syntax error in file ąĳŇ𨸋ûÍ: invalid character '²' (U+00B2) (<unknown>, line 1)
ERROR:root:Syntax error in file ąĳŇ𨸋ûÍ: invalid character '²' (U+00B2) (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid character '²' (U+00B2) (<unknown>, line 1)
ERROR:root:Syntax error in file ÖĠ: invalid decimal literal (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+2004 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid syntax (<unknown>, line 1)
ERROR:root:Syntax error in file 𭝧ċ#)þė;𦢢껗앦𣋢皆: invalid non-printable character U+134AD (<unknown>, line 1)
ERROR:root:Syntax error in file 𭝧ċ#)þė;𦢢껗앦𣋢皆: invalid non-printable character U+134AD (<unknown>, line 1)
ERROR:root:Syntax error in file 𭝧ċ#)þė;𦢢껗앦𣋢皆: invalid non-printable character U+134AD (<unknown>, line 1)
ERROR:root:Syntax error in file 𭝧ċ#)þė;𦢢껗앦𣋢皆: invalid non-printable character U+134AD (<unknown>, line 1)
ERROR:root:Syntax error in file 𭝧ċ#)þė;𦢢껗앦𣋢皆: invalid non-printable character U+134AD (<unknown>, line 1)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+0085 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
ERROR:root:Syntax error in file example.py: invalid non-printable character U+1680 (<unknown>, line 2)
